@startuml class
object User {
  id: integer PK
  idauth: varchar
  username: varchar(50)
  mail: varchar
}

object Relationship {
  id: integer PK
  user_relationship_type_id: integer FK
  name: varchar
}

object RelationshipType {
  id: integer PK
  name: varchar
}

object User_RelationshipType {
  id: integer PK
  user_id: integer FK
  relationship_type_id: integer FK
  reminder_day: day Null
}

object Payment {
  id: integer PK
  relationship_id: integer FK
  curreny: varchar(5) FK
  user_id: integer FK
  title: varchar(20)
  detail: varchar(280) Null
  amount: integer
  date: date
  type: varchar(3) deb|cre
  refunded: byte
  refunded_date: date Null
}

object ReminderDate {
  id: integer PK
  payment_id: integer FK
  date: date
}

Relationship "0..*" -- "1" User_RelationshipType
RelationshipType "1" -- "0..*" User_RelationshipType
User_RelationshipType "0..*" -- "1" User
Payment "0..*" -- "1" Relationship
Payment "0..*" -- "1" User
Payment "1" -- "0..*" ReminderDate
@enduml